"""empty message

Revision ID: 7c3b3d9a608f
Revises: 
Create Date: 2019-06-27 04:47:00.260480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c3b3d9a608f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    op.drop_table('about')
    op.drop_table('services')
    op.drop_table('serviceitem')
    op.drop_table('contacts')
    op.drop_table('footer')
    op.drop_table('header')
    op.add_column('portfolio', sa.Column('name', sa.VARCHAR(length=250), nullable=False))
    op.drop_column('portfolio', 'project_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('project_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('portfolio', 'name')
    op.create_table('header',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('background_image', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sub_title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('button_text', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('button_link', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='header_pkey')
    )
    op.create_table('footer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('copyright', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='footer_pkey')
    )
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contacts_pkey')
    )
    op.create_table('serviceitem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='serviceitem_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='serviceitem_pkey')
    )
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='services_pkey')
    )
    op.create_table('about',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sub_title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('button_text', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('button_link', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='about_pkey')
    )
    op.create_table('menu',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='menu_pkey')
    )
    # ### end Alembic commands ###
