# Generated by Django 2.2.3 on 2019-07-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
